{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhenxi",
    "module": "dex-cfg-obfuscator",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "dex-cfg-obfuscator-1.0.0.jar",
          "url": "dex-cfg-obfuscator-1.0.0.jar",
          "size": 52195,
          "sha512": "e131c8210e195b5f7e0af606ff93676bd0cce8dcbfca13a0c0a7f969e6394ccc6f47c604b3a7a8362a642138fb1b449e498efc57af122e8f20cb2f764a47ced2",
          "sha256": "3818d839cc43e375a03c2e050d5a9fcdaf4e188d380e4849f04ae30238cb807b",
          "sha1": "67ee677563e5db5c206badb747beda12c5de25c5",
          "md5": "2a7e8fd4cfdb2386ed62614e35a9c443"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.smali",
          "module": "smali-dexlib2",
          "version": {
            "requires": "3.0.9"
          }
        }
      ],
      "files": [
        {
          "name": "dex-cfg-obfuscator-1.0.0.jar",
          "url": "dex-cfg-obfuscator-1.0.0.jar",
          "size": 52195,
          "sha512": "e131c8210e195b5f7e0af606ff93676bd0cce8dcbfca13a0c0a7f969e6394ccc6f47c604b3a7a8362a642138fb1b449e498efc57af122e8f20cb2f764a47ced2",
          "sha256": "3818d839cc43e375a03c2e050d5a9fcdaf4e188d380e4849f04ae30238cb807b",
          "sha1": "67ee677563e5db5c206badb747beda12c5de25c5",
          "md5": "2a7e8fd4cfdb2386ed62614e35a9c443"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "dex-cfg-obfuscator-1.0.0-sources.jar",
          "url": "dex-cfg-obfuscator-1.0.0-sources.jar",
          "size": 15843,
          "sha512": "03c1af050c764ccbeeb8ddcb7131c016ecb83bc118341b8de50aacd72162be59c34c2eab1c61004fc49d9b84519f636b30d2327b5f5d410e47cc5cd7a20bde48",
          "sha256": "57478c27fd4820a5560eb0c3ef8fdcf18751f32881d925f2b93ec5d745f02fc6",
          "sha1": "dd662c0544819a0dd937656065a5898d621333ee",
          "md5": "2d40338369e9834893f831ffda263b3a"
        }
      ]
    }
  ]
}
