package com.hunter.dexcfgobf.string;

import org.gradle.api.DefaultTask;
import org.gradle.api.file.RegularFileProperty;
import org.gradle.api.provider.Property;
import org.gradle.api.tasks.CacheableTask;
import org.gradle.api.tasks.Input;
import org.gradle.api.tasks.OutputFile;
import org.gradle.api.tasks.TaskAction;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;

/** Generates the final-R8 rule that keeps exact encrypted-string method boundaries. */
@CacheableTask
public abstract class GenerateStringProtectionRulesTask extends DefaultTask {

    @Input
    public abstract Property<String> getMethodMarkerAnnotationClassName();

    @OutputFile
    public abstract RegularFileProperty getOutputFile();

    @TaskAction
    public void generate() throws Exception {
        String marker = validateClassName(getMethodMarkerAnnotationClassName().get());
        File output = getOutputFile().get().getAsFile();
        File parent = output.getParentFile();
        if (!parent.isDirectory() && !parent.mkdirs() && !parent.isDirectory()) {
            throw new java.io.IOException("cannot create generated R8 rules directory: " + parent);
        }
        Files.writeString(output.toPath(), renderRules(marker), StandardCharsets.UTF_8);
    }

    static String renderRules(String markerClassName) {
        String marker = validateClassName(markerClassName);
        return "# Generated by DexCfgObfuscator. Ordinary methods with encrypted strings keep "
                + "their R8 optimization boundary.\n"
                + "-keepclassmembers,allowshrinking,allowobfuscation class * {\n"
                + "    @" + marker + " <methods>;\n"
                + "}\n";
    }

    private static String validateClassName(String value) {
        String name = value == null ? "" : value.trim();
        if (!name.matches("[A-Za-z_$][A-Za-z0-9_$]*(\\.[A-Za-z_$][A-Za-z0-9_$]*)+")) {
            throw new IllegalArgumentException("invalid generated method marker class: " + value);
        }
        return name;
    }
}
