package com.hunter.dexcfgobf.string;

import org.gradle.api.DefaultTask;
import org.gradle.api.file.DirectoryProperty;
import org.gradle.api.provider.Property;
import org.gradle.api.tasks.CacheableTask;
import org.gradle.api.tasks.Input;
import org.gradle.api.tasks.OutputDirectory;
import org.gradle.api.tasks.TaskAction;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.Comparator;

/** 为每个 variant 生成一个很小的 Android 运行时解密桥，不引入独立 runtime artifact。 */
@CacheableTask
public abstract class GenerateStringDecryptorTask extends DefaultTask {

    @OutputDirectory
    public abstract DirectoryProperty getOutputDirectory();

    @Input
    public abstract Property<String> getBridgeClassName();

    @Input
    public abstract Property<String> getImplementationClassName();

    @Input
    public abstract Property<Boolean> getDecryptorStatic();

    @TaskAction
    public void generate() throws Exception {
        File root = getOutputDirectory().get().getAsFile();
        if (root.exists()) {
            try (java.util.stream.Stream<java.nio.file.Path> paths = Files.walk(root.toPath())) {
                paths.sorted(Comparator.reverseOrder()).forEach(path -> {
                    try {
                        Files.deleteIfExists(path);
                    } catch (java.io.IOException failure) {
                        throw new DeleteFailure(failure);
                    }
                });
            } catch (DeleteFailure failure) {
                throw failure.cause;
            }
        }
        String className = validateClassName(getBridgeClassName().get(), "bridgeClass");
        String implementation = getImplementationClassName().getOrElse("").trim();
        if (!implementation.isEmpty()) {
            validateClassName(implementation, "implementation");
        }
        int lastDot = className.lastIndexOf('.');
        String packageName = className.substring(0, lastDot);
        String simpleName = className.substring(lastDot + 1);
        if (simpleName.indexOf('$') >= 0) {
            throw new IllegalArgumentException("bridgeClass must be a top-level class: " + className);
        }
        File source = new File(root,
                packageName.replace('.', File.separatorChar) + File.separator + simpleName + ".java");
        File parent = source.getParentFile();
        if (!parent.isDirectory() && !parent.mkdirs() && !parent.isDirectory()) {
            throw new java.io.IOException("cannot create generated source directory: " + parent);
        }
        Files.writeString(source.toPath(), renderSource(packageName, simpleName, implementation,
                getDecryptorStatic().getOrElse(false)), StandardCharsets.UTF_8);
    }

    static String renderSource(String packageName, String simpleName, String implementation,
                               boolean decryptorStatic) {
        StringBuilder out = new StringBuilder(1800);
        out.append("package ").append(packageName).append(";\n\n")
                .append("/** Generated by DexCfgObfuscator. */\n")
                .append("public final class ").append(simpleName).append(" {\n")
                .append("  @java.lang.annotation.Retention(java.lang.annotation.RetentionPolicy.CLASS)\n")
                .append("  @java.lang.annotation.Target({java.lang.annotation.ElementType.METHOD, ")
                .append("java.lang.annotation.ElementType.CONSTRUCTOR})\n")
                .append("  public @interface ")
                .append(StringEncryptionContext.METHOD_MARKER_SIMPLE_NAME).append(" {}\n\n");
        if (implementation == null || implementation.isEmpty()) {
            out.append("  public static String decrypt(byte[] value, byte[] key) {\n")
                    .append("    if (key == null || key.length == 0) throw new IllegalArgumentException();\n")
                    .append("    byte[] output = new byte[value.length];\n")
                    .append("    int state = 0x6D2B79F5;\n")
                    .append("    for (byte b : key) state = (state * 33) ^ (b & 0xff);\n")
                    .append("    for (int i = 0; i < value.length; i++) {\n")
                    .append("      state ^= state << 13;\n")
                    .append("      state ^= state >>> 17;\n")
                    .append("      state ^= state << 5;\n")
                    .append("      int mask = state & 0xff;\n")
                    .append("      if (mask == 0) mask = 0xA5;\n")
                    .append("      output[i] = (byte) (value[i] ^ mask);\n")
                    .append("    }\n")
                    .append("    return new String(output, java.nio.charset.StandardCharsets.UTF_8).intern();\n")
                    .append("  }\n");
        } else {
            if (!decryptorStatic) {
                out.append("  private static final ").append(implementation).append(" IMPL = new ")
                        .append(implementation).append("();\n");
            }
            out.append("  public static String decrypt(byte[] value, byte[] key) {\n")
                    .append("    String result = ").append(decryptorStatic ? implementation : "IMPL")
                    .append(".decrypt(value, key);\n")
                    .append("    if (result == null) throw new IllegalStateException();\n")
                    .append("    return result.intern();\n")
                    .append("  }\n");
        }
        out.append("  public static String decrypt(String value, String key) {\n")
                .append("    return decrypt(android.util.Base64.decode(value, android.util.Base64.NO_WRAP),\n")
                .append("        android.util.Base64.decode(key, android.util.Base64.NO_WRAP));\n")
                .append("  }\n")
                .append("  private ").append(simpleName).append("() {}\n")
                .append("}\n");
        return out.toString();
    }

    private static String validateClassName(String value, String label) {
        String name = value == null ? "" : value.trim();
        if (!name.matches("[A-Za-z_$][A-Za-z0-9_$]*(\\.[A-Za-z_$][A-Za-z0-9_$]*)+")) {
            throw new IllegalArgumentException("invalid stringEncryption." + label + ": " + value);
        }
        return name;
    }

    private static final class DeleteFailure extends RuntimeException {
        final java.io.IOException cause;

        DeleteFailure(java.io.IOException cause) {
            super(cause);
            this.cause = cause;
        }
    }
}
